name: Deploy Website
on:
  push:
    branches: [main] # 当你推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Pre-process # 运行你的脚本修复格式
        run: node scripts/pre_process.js

      - name: Build VitePress
        run: npm run docs:build

      - name: Deploy to GitHub Pages # 自动发布
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
